// =============================================================================
// tripService.js — trip creation (transactional), itinerary + packing + budget.
//
// Itinerary and packing are now generated by the intelligence layer:
//   · itinerary → intelligence/trip/itineraryOptimizer.js (nearest-neighbour
//     ordering + time/cost estimates; selected places ONLY, generic fillers)
//   · packing   → intelligence/packing/packingEngine.js (context-aware rules,
//     ESSENTIAL/RECOMMENDED/OPTIONAL priorities)
// An LLM provider can still be layered on top later without changing callers.
// =============================================================================

import prisma from '../config/database.js';
import { badRequest, notFound, forbidden } from '../utils/errors.js';
import { optimizeItinerary } from '../intelligence/trip/itineraryOptimizer.js';
import { generatePackingPlan } from '../intelligence/packing/packingEngine.js';
import { isTripExpiredIST, isTripActiveIST, getNowIST } from '../utils/timeZone.js';

function timeToMinutes(t) {
  const m = (t || '').match(/(\d+):(\d+)\s*(AM|PM)/i);
  if (!m) return 0;
  let h = parseInt(m[1], 10);
  const min = parseInt(m[2], 10);
  if (m[3].toUpperCase() === 'PM' && h !== 12) h += 12;
  if (m[3].toUpperCase() === 'AM' && h === 12) h = 0;
  return h * 60 + min;
}

// Build the itinerary from SELECTED places only, via the optimizer.
function buildItinerary(places, durationDays) {
  const result = optimizeItinerary({
    places: places.map((p) => ({
      id: p.id,
      name: p.name,
      category: p.category,
      latitude: p.latitude ?? null,
      longitude: p.longitude ?? null,
      entryPrice: p.entryPrice
    })),
    durationDays: durationDays || 2
  });

  // Map to the storage shape (time/title/type/note/placeId).
  return result.itinerary.map((day) => ({
    day: day.day,
    activities: day.activities.map((a) => ({
      time: a.time,
      title: a.title,
      type: a.type,
      note: a.note || a.category || null,
      placeId: a.placeId || null
    }))
  }));
}

// Build the day-wise packing list from the itinerary via the packing engine.
function buildPacking(places, durationDays) {
  const days = durationDays || 2;
  const perDay = Math.ceil(places.length / days);

  const itinerary = [];
  for (let d = 1; d <= days; d++) {
    const dayPlaces = places.slice((d - 1) * perDay, d * perDay);
    itinerary.push({
      day: d,
      activities: dayPlaces.map((p) => ({ title: p.name, category: p.category }))
    });
  }

  const plan = generatePackingPlan({ itinerary, durationDays: days });
  return plan.map((d) => ({
    day: d.day,
    reason: d.reason,
    items: d.items.map((it) => ({ label: it.name, reason: it.reason, priority: it.priority }))
  }));
}

function buildBudget(total, memberCount) {
  const hotel = Math.round(total * 0.36);
  const food = Math.round(total * 0.24);
  const transport = Math.round(total * 0.18);
  const attractions = Math.round(total * 0.12);
  const entertainment = total - hotel - food - transport - attractions;
  return { hotel, food, transport, entertainment: Math.max(0, entertainment), attractions };
}

export function generateJoinCode(destination = '') {
  const cleanDest = (destination || '').replace(/[^A-Za-z]/g, '').toUpperCase().slice(0, 4);
  const prefix = cleanDest.length >= 3 ? cleanDest : 'ROYAL';
  const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  let suffix = '';
  const length = prefix.length === 3 ? 4 : 3;
  for (let i = 0; i < length; i++) {
    suffix += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return `${prefix}${suffix}`;
}

// --- Create trip (transactional) -------------------------------------------

export async function createTrip(userId, input) {
  const { destination, destinationAddress, latitude, longitude, startDate, endDate, dates, duration, durationDays, budget, group, memberCount, members, selectedPlaceIds } = input;

  if (!destination?.trim()) throw badRequest('Destination is required.');
  if (!budget || Number(budget) <= 0) throw badRequest('A valid budget is required.');
  if (!Array.isArray(selectedPlaceIds) || selectedPlaceIds.length === 0) {
    throw badRequest('At least one place must be selected.');
  }

  const creator = await prisma.user.findUnique({ where: { id: userId } });

  const normalizedMembers = (members || []).map((m, idx) => {
    if (typeof m === 'string') {
      const clean = m.replace(/\D/g, '').slice(-10);
      return { name: `Member ${idx + 1}`, phone: clean };
    }
    const clean = (m.phone || '').replace(/\D/g, '').slice(-10);
    return { name: m.name?.trim() || `Member ${idx + 1}`, phone: clean };
  });
  const uniqueMembers = [...new Map(normalizedMembers.filter((m) => m.phone).map((m) => [m.phone, m])).values()];

  const places = [];
  const placeIds = Array.isArray(selectedPlaceIds) ? selectedPlaceIds : [];

  if (placeIds.length > 0) {
    const existingPlaces = await prisma.place.findMany({ where: { id: { in: placeIds } } });
    const existingMap = new Map(existingPlaces.map((p) => [p.id, p]));

    for (const pid of placeIds) {
      if (existingMap.has(pid)) {
        places.push(existingMap.get(pid));
      } else {
        let poi = null;
        try {
          const { getItem } = await import('./discoverService.js');
          poi = await getItem('places', pid);
        } catch {
          // ignore
        }
        if (poi) {
          try {
            const dbPlace = await prisma.place.upsert({
              where: { id: pid },
              create: {
                id: pid,
                name: poi.name || 'Tourist Place',
                category: poi.category || 'Attractions',
                location: poi.address || destination || 'Tamil Nadu',
                address: poi.address || null,
                latitude: poi.latitude || (latitude != null ? Number(latitude) : 11.0168),
                longitude: poi.longitude || (longitude != null ? Number(longitude) : 76.9558),
                rating: poi.rating || 4.5,
                reviews: poi.reviews || 10,
                verified: true,
                source: poi.source || 'osm'
              },
              update: {}
            });
            places.push(dbPlace);
          } catch {
            // If upsert fails, continue
          }
        }
      }
    }
  }

  if (places.length === 0) {
    const defaultPlaceId = `place-${destination.toLowerCase().replace(/[^a-z0-9]/g, '-') || 'landmark'}`;
    const defaultPlace = await prisma.place.upsert({
      where: { id: defaultPlaceId },
      create: {
        id: defaultPlaceId,
        name: `${destination} Landmark`,
        category: 'Attractions',
        location: destination,
        latitude: latitude != null ? Number(latitude) : 11.0168,
        longitude: longitude != null ? Number(longitude) : 76.9558,
        rating: 4.8,
        reviews: 20,
        verified: true,
        source: 'system'
      },
      update: {}
    });
    places.push(defaultPlace);
  }

  const effectiveDuration = duration || '2 Days';
  const effectiveDays = durationDays || 2;
  const effectiveMemberCount = memberCount || Math.max(1, uniqueMembers.length + 1);

  const itinerary = buildItinerary(places, effectiveDays);
  const packing = buildPacking(places, effectiveDays);
  const budgetBreakdown = buildBudget(Number(budget), effectiveMemberCount);

  const formattedDates = dates || (startDate && endDate ? `${startDate} to ${endDate}` : null);
  const parsedStartDate = startDate ? new Date(startDate) : null;
  const parsedEndDate = endDate ? new Date(endDate) : null;

  const creatorCleanPhone = creator?.phone ? creator.phone.replace(/\D/g, '').slice(-10) : '';
  const firstMemberMatchesCreator = uniqueMembers.length > 0 && (
    uniqueMembers[0].phone === creatorCleanPhone ||
    (creator?.name && uniqueMembers[0].name.toLowerCase().includes(creator.name.toLowerCase().split(' ')[0]))
  );

  const resolvedMembers = [
    {
      name: (firstMemberMatchesCreator ? uniqueMembers[0].name : creator?.name) || 'Organizer',
      phone: (firstMemberMatchesCreator ? uniqueMembers[0].phone : creator?.phone) || '—',
      userId: userId,
      role: 'Owner',
      status: 'ACCEPTED'
    }
  ];
  const invitedUsersToNotify = [];

  const startIndex = firstMemberMatchesCreator ? 1 : 0;
  for (let i = startIndex; i < uniqueMembers.length; i++) {
    const cleanPhone = uniqueMembers[i].phone;
    const mName = uniqueMembers[i].name;

    const registeredUser = await prisma.user.findFirst({
      where: {
        phone: { contains: cleanPhone }
      }
    });

    const memberUserId = registeredUser ? registeredUser.id : null;
    if (memberUserId === userId || (cleanPhone && cleanPhone === creatorCleanPhone)) {
      continue;
    }

    resolvedMembers.push({
      name: registeredUser?.name || mName,
      phone: registeredUser?.phone || cleanPhone,
      userId: memberUserId,
      role: 'Member',
      status: 'ACCEPTED'
    });

    if (registeredUser && registeredUser.id !== userId) {
      invitedUsersToNotify.push(registeredUser);
    }
  }

  // =========================================================================
  // Duplicate Trip Validation:
  // ONLY block when ALL 4 conditions match:
  // 1. Same user / trip owner
  // 2. Same trip start date
  // 3. Same trip end date
  // 4. Same team members (order-insensitive, normalized identifiers)
  // =========================================================================
  if (parsedStartDate && parsedEndDate) {
    const existingTrips = await prisma.trip.findMany({
      where: { userId },
      include: { members: true }
    });

    const toDateString = (d) => {
      if (!d) return '';
      try {
        const dt = new Date(d);
        return isNaN(dt.getTime()) ? '' : dt.toISOString().split('T')[0];
      } catch {
        return '';
      }
    };

    const newStartStr = toDateString(parsedStartDate);
    const newEndStr = toDateString(parsedEndDate);

    const getMemberKey = (m) => {
      if (m.userId) return `user:${m.userId}`;
      const cleanPhone = (m.phone || '').replace(/\D/g, '').slice(-10);
      return cleanPhone ? `phone:${cleanPhone}` : `name:${(m.name || '').trim().toLowerCase()}`;
    };

    const newMemberFingerprint = resolvedMembers.map(getMemberKey).sort().join('|');

    const duplicateTrip = existingTrips.find((t) => {
      const existingStartStr = toDateString(t.startDate);
      const existingEndStr = toDateString(t.endDate);
      if (existingStartStr !== newStartStr || existingEndStr !== newEndStr) {
        return false;
      }

      const existingMemberFingerprint = (t.members || []).map(getMemberKey).sort().join('|');
      return existingMemberFingerprint === newMemberFingerprint;
    });

    if (duplicateTrip) {
      throw badRequest('Already a trip is planned on these dates with the same members.');
    }
  }

  // Generate unique join code for the new trip
  let joinCode = '';
  let attempts = 0;
  while (!joinCode && attempts < 30) {
    const candidate = generateJoinCode(destination);
    const existing = await prisma.trip.findUnique({ where: { joinCode: candidate } });
    if (!existing) {
      joinCode = candidate;
    }
    attempts++;
  }
  if (!joinCode) {
    joinCode = `ROYAL${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
  }

  const trip = await prisma.$transaction(async (tx) => {
    const t = await tx.trip.create({
      data: {
        userId,
        destination: destination.trim(),
        destinationAddress: destinationAddress ? destinationAddress.trim() : null,
        latitude: latitude != null ? Number(latitude) : null,
        longitude: longitude != null ? Number(longitude) : null,
        startDate: parsedStartDate,
        endDate: parsedEndDate,
        dates: formattedDates,
        duration,
        durationDays: durationDays || 2,
        groupType: group,
        memberCount: resolvedMembers.filter((m) => m.status === 'ACCEPTED').length,
        budget: Number(budget),
        joinCode
      }
    });

    await tx.tripMember.createMany({
      data: resolvedMembers.map((m) => ({
        tripId: t.id,
        name: m.name,
        phone: m.phone,
        userId: m.userId,
        role: m.role,
        status: m.status
      }))
    });

    await tx.tripPlace.createMany({
      data: places.map((p, i) => ({
        tripId: t.id,
        placeId: p.id,
        day: Math.floor(i / Math.ceil(places.length / (durationDays || 2))) + 1
      }))
    });

    for (const day of itinerary) {
      const d = await tx.itineraryDay.create({ data: { tripId: t.id, day: day.day } });
      await tx.itineraryActivity.createMany({
        data: day.activities.map((a) => ({ dayId: d.id, time: a.time, title: a.title, type: a.type, note: a.note, placeId: a.placeId }))
      });
    }

    for (const p of packing) {
      const pd = await tx.packingDay.create({ data: { tripId: t.id, day: p.day, reason: p.reason } });
      await tx.packingItem.createMany({
        data: p.items.map((it) => ({ dayId: pd.id, label: it.label, reason: it.reason, priority: it.priority }))
      });
    }

    await tx.tripBudget.create({ data: { tripId: t.id, ...budgetBreakdown } });

    // Persist in-app notifications for invited users in PostgreSQL
    for (const invitedUser of invitedUsersToNotify) {
      const existingInvite = await tx.notification.findFirst({
        where: {
          userId: invitedUser.id,
          type: 'TRIP_INVITE',
          status: 'PENDING',
          payload: { contains: `\"tripId\":\"${t.id}\"` }
        }
      });
      if (!existingInvite) await tx.notification.create({
        data: {
          userId: invitedUser.id,
          type: 'TRIP_INVITE',
          channel: 'IN_APP',
          status: 'PENDING',
          content: `${creator?.name || 'Trip Leader'} invited you to join a trip to ${t.destination}!`,
          payload: JSON.stringify({
            tripId: t.id,
            destination: t.destination,
            creatorName: creator?.name || 'Trip Leader',
            dates: formattedDates || 'Upcoming',
            duration: t.duration,
            groupType: t.groupType
          })
        }
      });
    }

    return t;
  });

  // Real-time broadcast to invited users' Socket.IO accounts
  try {
    const { getIO } = await import('../realtime/socket.js');
    const io = getIO();
    if (io) {
      for (const invitedUser of invitedUsersToNotify) {
        const invitePayload = {
          id: `invite-${trip.id}-${Date.now()}`,
          tripId: trip.id,
          destination: trip.destination,
          creatorName: creator?.name || 'Trip Leader',
          dates: formattedDates || 'Upcoming',
          duration: trip.duration,
          title: 'Trip Invitation',
          message: `${creator?.name || 'Trip Leader'} invited you to join a travel group for ${trip.destination}!`,
          type: 'TRIP_INVITE',
          timestamp: new Date().toISOString()
        };
        io.to(`user:${invitedUser.id}`).emit('trip:invitation', invitePayload);
        io.to(`user:${invitedUser.id}`).emit('group:notification', invitePayload);
      }
    }
  } catch {
    // Socket broadcast non-fatal fallback
  }

  return trip;
}

export async function acceptInvitation(tripId, userId) {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw notFound('User not found.');

  const trip = await prisma.trip.findUnique({ where: { id: tripId }, include: { members: true, user: true } });
  if (!trip) throw notFound('Trip not found.');

  const cleanPhone = user.phone.replace(/\D/g, '').slice(-10);
  const member = trip.members.find((m) => m.userId === userId || m.phone.replace(/\D/g, '').slice(-10) === cleanPhone);

  if (!member) {
    throw badRequest('No invitation found for this trip.');
  }

  const updatedMember = await prisma.tripMember.update({
    where: { id: member.id },
    data: {
      userId: user.id,
      status: 'ACCEPTED',
      online: true
    }
  });

  await resolveInvitationNotification(tripId, userId);

  const acceptedCount = await prisma.tripMember.count({ where: { tripId, status: 'ACCEPTED' } });
  await prisma.trip.update({ where: { id: tripId }, data: { memberCount: acceptedCount } });

  // Real-time notification to trip creator and group room
  try {
    const { getIO } = await import('../realtime/socket.js');
    const io = getIO();
    if (io) {
      io.to(`user:${trip.userId}`).emit('trip:invitation:accepted', {
        tripId,
        userId: user.id,
        userName: user.name,
        message: `${user.name} accepted your trip invitation to ${trip.destination}!`
      });
      io.to(`group:${tripId}`).emit('group:member:joined', {
        tripId,
        userId: user.id,
        name: user.name,
        member: { id: updatedMember.id, userId: user.id, name: user.name, phone: user.phone, role: 'Member', status: 'ACCEPTED' }
      });
    }
  } catch {
    // ignore
  }

  return getTrip(tripId);
}

export async function rejectInvitation(tripId, userId) {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw notFound('User not found.');

  const trip = await prisma.trip.findUnique({ where: { id: tripId }, include: { members: true } });
  if (!trip) throw notFound('Trip not found.');

  const cleanPhone = user.phone.replace(/\D/g, '').slice(-10);
  const member = trip.members.find((m) => m.userId === userId || m.phone.replace(/\D/g, '').slice(-10) === cleanPhone);

  if (member) {
    await prisma.tripMember.update({
      where: { id: member.id },
      data: { status: 'REJECTED' }
    });
  }

  await resolveInvitationNotification(tripId, userId);

  // Real-time notification to trip creator
  try {
    const { getIO } = await import('../realtime/socket.js');
    const io = getIO();
    if (io) {
      io.to(`user:${trip.userId}`).emit('trip:invitation:rejected', {
        tripId,
        userId: user.id,
        userName: user.name,
        message: `${user.name} declined the trip invitation to ${trip.destination}.`
      });
    }
  } catch {
    // ignore
  }

  return { success: true, tripId };
}

async function resolveInvitationNotification(tripId, userId) {
  const records = await prisma.notification.findMany({
    where: { userId, type: 'TRIP_INVITE', status: 'PENDING' }
  });
  for (const record of records) {
    try {
      if (JSON.parse(record.payload || '{}').tripId === tripId) {
        await prisma.notification.update({ where: { id: record.id }, data: { status: 'SENT' } });
      }
    } catch {
      // Ignore malformed legacy notification payloads.
    }
  }
}

export function isTripExpired(trip, now = getNowIST()) {
  return isTripExpiredIST(trip, now);
}

export async function checkAndExpireTrips() {
  try {
    const now = getNowIST();
    const activeTrips = await prisma.trip.findMany({
      where: { status: 'active' },
      select: {
        id: true,
        startDate: true,
        endDate: true,
        dates: true,
        durationDays: true,
        status: true
      }
    });

    for (const trip of activeTrips) {
      if (isTripExpiredIST(trip, now)) {
        await prisma.trip.update({
          where: { id: trip.id },
          data: { status: 'completed' }
        });

        // Expire active group memberships (status changed from ACCEPTED to EXPIRED)
        // Member records remain intact for historical trip details viewing!
        await prisma.tripMember.updateMany({
          where: {
            tripId: trip.id,
            status: 'ACCEPTED'
          },
          data: {
            status: 'EXPIRED',
            online: false
          }
        });
      }
    }
  } catch (err) {
    console.error('Error during checkAndExpireTrips:', err);
  }
}

// Background scheduler to auto-expire trips every 60s
if (process.env.NODE_ENV !== 'test') {
  const timer = setInterval(() => {
    checkAndExpireTrips().catch(() => {});
  }, 60000);
  if (timer.unref) timer.unref();
}

export async function getTrip(tripId) {
  await checkAndExpireTrips();
  const trip = await prisma.trip.findUnique({
    where: { id: tripId },
    include: {
      user: { select: { id: true, name: true, phone: true } },
      members: {
        include: { user: { select: { id: true, name: true, phone: true, avatarUrl: true } } },
        orderBy: { createdAt: 'desc' }
      },
      places: { include: { place: true } },
      itinerary: {
        orderBy: { day: 'asc' },
        include: { activities: { orderBy: { time: 'asc' } } }
      },
      packing: {
        orderBy: { day: 'asc' },
        include: { items: true }
      },
      budgetBreakdown: true,
      expenses: { orderBy: [{ spentAt: 'desc' }, { createdAt: 'desc' }] }
    }
  });
  if (!trip) throw notFound('Trip not found.');

  // Resolve member user profiles by phone if userId is null
  if (Array.isArray(trip.members)) {
    const unlinked = trip.members.filter((m) => !m.user && m.phone);
    if (unlinked.length > 0) {
      const phones = unlinked.map((m) => m.phone.replace(/\D/g, '').slice(-10)).filter(Boolean);
      if (phones.length > 0) {
        const users = await prisma.user.findMany({
          where: { phone: { in: phones } },
          select: { id: true, name: true, phone: true, avatarUrl: true }
        });
        const uMap = new Map(users.map((u) => [u.phone.replace(/\D/g, '').slice(-10), u]));
        trip.members = trip.members.map((m) => {
          if (!m.user && m.phone) {
            const cp = m.phone.replace(/\D/g, '').slice(-10);
            const u = uMap.get(cp);
            if (u) return { ...m, userId: u.id, user: u, name: u.name || m.name };
          }
          return m;
        });
      }
    }
  }

  // Exclude LEFT/REMOVED members from active trips completely
  const isTripActive = trip.status === 'active' && !isTripExpired(trip);
  if (isTripActive) {
    const leftMembers = trip.members.filter((m) => ['LEFT', 'REMOVED'].includes(m.status));
    const leftUserIds = new Set(leftMembers.map((m) => m.userId).filter(Boolean));
    const leftPhones = new Set(leftMembers.map((m) => m.phone ? m.phone.replace(/\D/g, '').slice(-10) : '').filter(Boolean));
    const leftNames = new Set(leftMembers.map((m) => m.name ? m.name.toLowerCase().trim() : '').filter(Boolean));

    const seenIdentities = new Set();
    trip.members = trip.members.filter((m) => {
      if (['LEFT', 'REMOVED'].includes(m.status)) return false;
      if (m.userId && leftUserIds.has(m.userId)) return false;
      const cleanPhone = m.phone ? m.phone.replace(/\D/g, '').slice(-10) : '';
      if (cleanPhone && leftPhones.has(cleanPhone)) return false;
      if (m.name && leftNames.has(m.name.toLowerCase().trim())) return false;

      const identity = m.userId || (cleanPhone ? `phone-${cleanPhone}` : m.id);
      if (seenIdentities.has(identity)) return false;
      seenIdentities.add(identity);
      return true;
    });
  }

  return trip;
}

export async function listTrips(userId) {
  await checkAndExpireTrips();
  const user = await prisma.user.findUnique({ where: { id: userId } });
  const cleanPhone = user?.phone ? user.phone.replace(/\D/g, '').slice(-10) : '';

  const trips = await prisma.trip.findMany({
    where: {
      OR: [
        { userId },
        {
          members: {
            some: {
              OR: [
                { userId, status: { in: ['ACCEPTED', 'EXPIRED', 'COMPLETED', 'LEFT'] } },
                ...(cleanPhone ? [{ phone: { contains: cleanPhone }, status: { in: ['ACCEPTED', 'EXPIRED', 'COMPLETED', 'LEFT'] } }] : [])
              ]
            }
          }
        }
      ]
    },
    orderBy: { createdAt: 'desc' },
    include: {
      user: { select: { id: true, name: true, phone: true } },
      members: {
        include: { user: { select: { id: true, name: true, phone: true, avatarUrl: true } } },
        orderBy: { createdAt: 'desc' }
      },
      places: { include: { place: true } },
      itinerary: { orderBy: { day: 'asc' }, include: { activities: { orderBy: { time: 'asc' } } } },
      packing: { orderBy: { day: 'asc' }, include: { items: true } },
      budgetBreakdown: true,
      expenses: { orderBy: [{ spentAt: 'desc' }, { createdAt: 'desc' }] }
    }
  });

  return trips.map((trip) => {
    // Detect if current user/caller explicitly left this trip
    const callerLeft = trip.members.some((m) => (
      (m.userId && m.userId === userId) ||
      (cleanPhone && m.phone && m.phone.replace(/\D/g, '').slice(-10) === cleanPhone)
    ) && m.status === 'LEFT');

    const isTripActive = trip.status === 'active' && !isTripExpired(trip);
    if (isTripActive) {
      const leftMembers = trip.members.filter((m) => ['LEFT', 'REMOVED'].includes(m.status));
      const leftUserIds = new Set(leftMembers.map((m) => m.userId).filter(Boolean));
      const leftPhones = new Set(leftMembers.map((m) => m.phone ? m.phone.replace(/\D/g, '').slice(-10) : '').filter(Boolean));
      const leftNames = new Set(leftMembers.map((m) => m.name ? m.name.toLowerCase().trim() : '').filter(Boolean));

      const seenIdentities = new Set();
      trip.members = trip.members.filter((m) => {
        if (['LEFT', 'REMOVED'].includes(m.status)) return false;
        if (m.userId && leftUserIds.has(m.userId)) return false;
        const cPhone = m.phone ? m.phone.replace(/\D/g, '').slice(-10) : '';
        if (cPhone && leftPhones.has(cPhone)) return false;
        if (m.name && leftNames.has(m.name.toLowerCase().trim())) return false;

        const identity = m.userId || (cPhone ? `phone-${cPhone}` : m.id);
        if (seenIdentities.has(identity)) return false;
        seenIdentities.add(identity);
        return true;
      });
    } else {
      // Completed trip history
      const leftMembers = trip.members.filter((m) => m.status === 'LEFT');
      const leftUserIds = new Set(leftMembers.map((m) => m.userId).filter(Boolean));
      const leftPhones = new Set(leftMembers.map((m) => m.phone ? m.phone.replace(/\D/g, '').slice(-10) : '').filter(Boolean));
      if (leftUserIds.size > 0 || leftPhones.size > 0) {
        trip.members = trip.members.map((m) => {
          const cPhone = m.phone ? m.phone.replace(/\D/g, '').slice(-10) : '';
          if ((m.userId && leftUserIds.has(m.userId)) || (cPhone && leftPhones.has(cPhone))) {
            return { ...m, status: 'LEFT', online: false };
          }
          return m;
        });
      }
    }
    return {
      ...trip,
      userHasLeft: callerLeft
    };
  });
}

export async function togglePackingItem(tripId, itemId) {
  const item = await prisma.packingItem.findFirst({
    where: { id: itemId, day: { tripId } }
  });
  if (!item) throw notFound('Packing item not found.');
  return prisma.packingItem.update({
    where: { id: itemId },
    data: { packed: !item.packed }
  });
}

// --- AI Re-plan: regenerate itinerary + packing + budget --------------------

export async function replanTrip(tripId, userId, { budget, duration, durationDays, selectedPlaceIds }) {
  const trip = await prisma.trip.findUnique({ where: { id: tripId } });
  if (!trip) throw notFound('Trip not found.');
  if (trip.userId !== userId) throw forbidden('You do not own this trip.');
  if (!Array.isArray(selectedPlaceIds) || selectedPlaceIds.length === 0) {
    throw badRequest('Select at least one tourist place.');
  }

  const places = await prisma.place.findMany({ where: { id: { in: selectedPlaceIds } } });
  if (places.length === 0) throw badRequest('No valid places selected.');

  const days = durationDays || trip.durationDays || 2;
  const itinerary = buildItinerary(places, days);
  const packing = buildPacking(places, days);
  const budgetBreakdown = buildBudget(Number(budget) || trip.budget, trip.memberCount);

  await prisma.$transaction(async (tx) => {
    await tx.trip.update({
      where: { id: tripId },
      data: {
        budget: Number(budget) || trip.budget,
        duration: duration || trip.duration,
        durationDays: days
      }
    });
    await tx.itineraryActivity.deleteMany({ where: { day: { tripId } } });
    await tx.itineraryDay.deleteMany({ where: { tripId } });
    await tx.packingItem.deleteMany({ where: { day: { tripId } } });
    await tx.packingDay.deleteMany({ where: { tripId } });
    await tx.tripBudget.deleteMany({ where: { tripId } });
    await tx.tripPlace.deleteMany({ where: { tripId } });

    await tx.tripPlace.createMany({
      data: places.map((p, i) => ({
        tripId,
        placeId: p.id,
        day: Math.floor(i / Math.ceil(places.length / days)) + 1
      }))
    });
    for (const day of itinerary) {
      const d = await tx.itineraryDay.create({ data: { tripId, day: day.day } });
      await tx.itineraryActivity.createMany({
        data: day.activities.map((a) => ({ dayId: d.id, time: a.time, title: a.title, type: a.type, note: a.note, placeId: a.placeId }))
      });
    }
    for (const p of packing) {
      const pd = await tx.packingDay.create({ data: { tripId, day: p.day, reason: p.reason } });
      await tx.packingItem.createMany({
        data: p.items.map((it) => ({ dayId: pd.id, label: it.label, reason: it.reason, priority: it.priority }))
      });
    }
    await tx.tripBudget.create({ data: { tripId, ...budgetBreakdown } });
  });

  return getTrip(tripId);
}

// --- Manual itinerary activity (generic activities only) ---------------------

export async function addItineraryActivity(tripId, userId, { day, time, title, type, note }) {
  const trip = await prisma.trip.findUnique({ where: { id: tripId } });
  if (!trip) throw notFound('Trip not found.');
  if (trip.userId !== userId) throw forbidden('You do not own this trip.');
  if (!day || !title?.trim()) throw badRequest('Activity title and day are required.');

  let dayRecord = await prisma.itineraryDay.findFirst({ where: { tripId, day } });
  if (!dayRecord) {
    dayRecord = await prisma.itineraryDay.create({ data: { tripId, day } });
  }
  return prisma.itineraryActivity.create({
    data: {
      dayId: dayRecord.id,
      time: time || '10:00 AM',
      title: title.trim(),
      type: type || 'Free Time',
      note: note || null
    }
  });
}
